language: php

sudo: false

cache:
  directory:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer --diff --dry-run --verbose fix

notifications:
  email: false
